image: gitpod/workspace-rust
tasks:
  - init: |
      sudo apt update
      sudo apt install cmake binaryen -y
      [ $FOLDER ] && gp open contracts/$FOLDER/src/lib.rs
      clear
vscode:
  extensions:
    - rust-lang.rust-analyzer
